stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project RSS_Reader.xcodeproj -scheme RSS_Reader
    - xcodebuild -project RSS_Reader.xcodeproj -scheme RSS_Reader -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.2'
    - xcodebuild -project RSS_Reader.xcodeproj -scheme Tests -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.2' test
    
