name: Tests

on: [push, pull_request]

jobs:
  compile:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - run: xcodebuild -project RSS_Reader.xcodeproj -scheme Run -destination 'platform=iOS Simulator,name=iPhone 12'
        
  unit_tests:
    runs-on: macos-latest
    
    needs: compile

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - run: xcodebuild -project RSS_Reader.xcodeproj -scheme Tests -destination 'platform=iOS Simulator,name=iPhone 12' test
