name: Tests

on: [push, pull_request]

jobs:
  clean:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - run: ls -la
    
    - name: Clean Workdir
      run: xcodebuild clean -project RSS_Reader.xcodeproj -scheme Run
    
  compile:
    runs-on: self-hosted
    
    needs: clean

    steps:
    - run: xcodebuild -project RSS_Reader.xcodeproj -scheme Run -destination 'platform=iOS Simulator,name=iPhone 12'
        
  unit_tests:
    runs-on: self-hosted
    
    needs: compile

    steps:
    - run: xcodebuild -project RSS_Reader.xcodeproj -scheme Tests -destination 'platform=iOS Simulator,name=iPhone 12' test
